# Generated by Django 3.1.5 on 2021-01-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('itemID', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('itemName', models.CharField(default='product 1', max_length=30, unique=True)),
                ('itemPrice', models.FloatField()),
                ('itemType', models.CharField(choices=[('service', 'service'), ('product', 'product')], default='product', max_length=7)),
            ],
            options={
                'verbose_name': 'products',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.products',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.products',),
        ),
    ]
